name: quiz_castle
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sensors: ^2.0.3
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2

  cupertino_icons: ^1.0.2
  simple_gradient_text: ^1.2.4
  http: ^0.13.5
  html: ^0.15.1
  html_unescape: ^2.0.0
  font_awesome_flutter: ^10.3.0

flutter_icons:
  image_path: "lib/assets/icon.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/